// Generated from AppSettingsView.logoOptions in the MACE app, so the picker
// here lists exactly what the app lists, in the same order and grouping.

export const LOGO_OPTIONS = [
  { value: 'logo', label: "Default", file: 'default', group: 'Default & Seasons' },
  { value: 'random', label: "Random", file: null, group: 'Default & Seasons' },
  { value: 'logo_spring', label: "Spring", file: 'spring', group: 'Default & Seasons' },
  { value: 'logo_summer', label: "Summer", file: 'summer', group: 'Default & Seasons' },
  { value: 'logo_fall', label: "Fall", file: 'fall', group: 'Default & Seasons' },
  { value: 'logo_winter', label: "Winter", file: 'winter', group: 'Default & Seasons' },
  { value: 'logo_new_years', label: "New Year's", file: 'new-year-s', group: 'Holidays' },
  { value: 'logo_valentines', label: "Valentine's Day", file: 'valentine-s-day', group: 'Holidays' },
  { value: 'logo_stpatricks', label: "St. Patrick's Day", file: 'st-patrick-s-day', group: 'Holidays' },
  { value: 'logo_easter', label: "Easter", file: 'easter', group: 'Holidays' },
  { value: 'logo_pride', label: "Pride", file: 'pride', group: 'Holidays' },
  { value: 'logo_birthday', label: "Birthday", file: 'birthday', group: 'Holidays' },
  { value: 'logo_independence', label: "Independence Day", file: 'independence-day', group: 'Holidays' },
  { value: 'logo_peace', label: "Day of Peace", file: 'day-of-peace', group: 'Holidays' },
  { value: 'logo_halloween', label: "Halloween", file: 'halloween', group: 'Holidays' },
  { value: 'logo_thanksgiving', label: "Thanksgiving", file: 'thanksgiving', group: 'Holidays' },
  { value: 'logo_christmas', label: "Christmas", file: 'christmas', group: 'Holidays' },
  { value: 'logo_mlk_day', label: "MLK Day", file: 'mlk-day', group: 'National Days' },
  { value: 'logo_mac_day', label: "Mac Day", file: 'mac-day', group: 'National Days' },
  { value: 'logo_lunar_new_year', label: "Lunar New Year", file: 'lunar-new-year', group: 'National Days' },
  { value: 'logo_puzzle', label: "National Puzzle Day", file: 'national-puzzle-day', group: 'National Days' },
  { value: 'logo_hot_chocolate', label: "National Hot Chocolate Day", file: 'national-hot-chocolate-day', group: 'National Days' },
  { value: 'logo_groundhog', label: "Groundhog Day", file: 'groundhog-day', group: 'National Days' },
  { value: 'logo_pizza', label: "National Pizza Day", file: 'national-pizza-day', group: 'National Days' },
  { value: 'logo_presidents_day', label: "Presidents Day", file: 'presidents-day', group: 'National Days' },
  { value: 'logo_pi', label: "National Pi Day", file: 'national-pi-day', group: 'National Days' },
  { value: 'logo_april_fools', label: "April Fools' Day", file: 'april-fools-day', group: 'National Days' },
  { value: 'logo_april_fools_2', label: "April Fools' Day (Alt)", file: 'april-fools-day-alt', group: 'National Days' },
  { value: 'logo_tax_day', label: "Tax Day", file: 'tax-day', group: 'National Days' },
  { value: 'logo_national_earth_day', label: "Earth Day", file: 'earth-day', group: 'National Days' },
  { value: 'logo_star_wars', label: "Star Wars Day", file: 'star-wars-day', group: 'National Days' },
  { value: 'logo_cinco_de_mayo', label: "Cinco de Mayo", file: 'cinco-de-mayo', group: 'National Days' },
  { value: 'logo_mothers_day', label: "Mother's Day", file: 'mother-s-day', group: 'National Days' },
  { value: 'logo_memorial_day', label: "Memorial Day", file: 'memorial-day', group: 'National Days' },
  { value: 'logo_donut', label: "National Donut Day", file: 'national-donut-day', group: 'National Days' },
  { value: 'logo_fathers_day', label: "Father's Day", file: 'father-s-day', group: 'National Days' },
  { value: 'logo_canada_day', label: "Canada Day", file: 'canada-day', group: 'National Days' },
  { value: 'logo_bastille_day', label: "Bastille Day", file: 'bastille-day', group: 'National Days' },
  { value: 'logo_cherry_day', label: "National Cherry Day", file: 'national-cherry-day', group: 'National Days' },
  { value: 'logo_ice_cream', label: "National Ice Cream Day", file: 'national-ice-cream-day', group: 'National Days' },
  { value: 'logo_shark_week', label: "Shark Week", file: 'shark-week', group: 'National Days' },
  { value: 'logo_sysadmin_day', label: "SysAdmin Day", file: 'sysadmin-day', group: 'National Days' },
  { value: 'logo_cat_day', label: "International Cat Day", file: 'international-cat-day', group: 'National Days' },
  { value: 'logo_smores', label: "National S'mores Day", file: 'national-s-mores-day', group: 'National Days' },
  { value: 'logo_relaxation_day', label: "National Relaxation Day", file: 'national-relaxation-day', group: 'National Days' },
  { value: 'logo_dog_day', label: "National Dog Day", file: 'national-dog-day', group: 'National Days' },
  { value: 'logo_labor_day', label: "Labor Day", file: 'labor-day', group: 'National Days' },
  { value: 'logo_programmers_day', label: "Programmers' Day", file: 'programmers-day', group: 'National Days' },
  { value: 'logo_pirate_day', label: "Talk Like a Pirate Day", file: 'talk-like-a-pirate-day', group: 'National Days' },
  { value: 'logo_coffee', label: "National Coffee Day", file: 'national-coffee-day', group: 'National Days' },
  { value: 'logo_oktoberfest', label: "Oktoberfest", file: 'oktoberfest', group: 'National Days' },
  { value: 'logo_mental_health', label: "Mental Health Day", file: 'mental-health-day', group: 'National Days' },
  { value: 'logo_dessert_day', label: "National Dessert Day", file: 'national-dessert-day', group: 'National Days' },
  { value: 'logo_dia_de_muertos', label: "Día de los Muertos", file: 'dia-de-los-muertos', group: 'National Days' },
  { value: 'logo_veterans_day', label: "Veterans Day", file: 'veterans-day', group: 'National Days' },
  { value: 'logo_pickle', label: "National Pickle Day", file: 'national-pickle-day', group: 'National Days' },
  { value: 'logo_computer_security', label: "Computer Security Day", file: 'computer-security-day', group: 'National Days' },
  { value: 'logo_cookie', label: "National Cookie Day", file: 'national-cookie-day', group: 'National Days' },
  { value: 'logo_airforce', label: "Air Force", file: 'air-force', group: 'Characters' },
  { value: 'logo_army', label: "Army", file: 'army', group: 'Characters' },
  { value: 'logo_astronaut', label: "Astronaut", file: 'astronaut', group: 'Characters' },
  { value: 'logo_beach_ball', label: "Beach Ball", file: 'beach-ball', group: 'Characters' },
  { value: 'logo_bob_ross', label: "Bob Ross", file: 'bob-ross', group: 'Characters' },
  { value: 'logo_cop', label: "Cop", file: 'cop', group: 'Characters' },
  { value: 'logo_corporate', label: "Corporate", file: 'corporate', group: 'Characters' },
  { value: 'logo_gov_guy', label: "Government", file: 'government', group: 'Characters' },
  { value: 'logo_hawaiian', label: "Hawaiian", file: 'hawaiian', group: 'Characters' },
  { value: 'logo_hipster', label: "Hipster", file: 'hipster', group: 'Characters' },
  { value: 'logo_marine', label: "Marine", file: 'marine', group: 'Characters' },
  { value: 'logo_paramedic', label: "Paramedic", file: 'paramedic', group: 'Characters' },
  { value: 'logo_sailor', label: "Sailor", file: 'sailor', group: 'Characters' },
  { value: 'logo_secret_service', label: "Secret Service", file: 'secret-service', group: 'Characters' },
  { value: 'logo_spaceforce', label: "Space Force", file: 'space-force', group: 'Characters' },
  { value: 'logo_steve_jobs', label: "Steve Jobs", file: 'steve-jobs', group: 'Characters' },
  { value: 'logo_terminal_wizard', label: "Terminal Wizard", file: 'terminal-wizard', group: 'Characters' },
];

export const LOGO_GROUPS = ['Default & Seasons', 'Holidays', 'National Days', 'Characters'];

export const ASSET_TO_FILE = Object.fromEntries(
  LOGO_OPTIONS.filter((o) => o.file).map((o) => [o.value, o.file]),
);

export const ASSET_TO_LABEL = Object.fromEntries(
  LOGO_OPTIONS.map((o) => [o.value, o.label]),
);
