// Auto-generated from the MACE logo set. Files live in static/img/logos/.
const LOGOS = [
  {name: "Air Force", file: "air-force.webp"},
  {name: "April Fools' Day (Alt)", file: "april-fools-day-alt.webp"},
  {name: "April Fools' Day", file: "april-fools-day.webp"},
  {name: "Army", file: "army.webp"},
  {name: "Astronaut", file: "astronaut.webp"},
  {name: "Bastille Day", file: "bastille-day.webp"},
  {name: "Beach Ball", file: "beach-ball.webp"},
  {name: "Binary", file: "binary.webp"},
  {name: "Birthday", file: "birthday.webp"},
  {name: "Bob Ross", file: "bob-ross.webp"},
  {name: "Canada Day", file: "canada-day.webp"},
  {name: "Christmas", file: "christmas.webp"},
  {name: "Cinco de Mayo", file: "cinco-de-mayo.webp"},
  {name: "Computer Security Day", file: "computer-security-day.webp"},
  {name: "Cop", file: "cop.webp"},
  {name: "Corporate", file: "corporate.webp"},
  {name: "Day of Peace", file: "day-of-peace.webp"},
  {name: "Default", file: "default.webp"},
  {name: "Dia de los Muertos", file: "dia-de-los-muertos.webp"},
  {name: "Earth Day", file: "earth-day.webp"},
  {name: "Easter", file: "easter.webp"},
  {name: "Fall", file: "fall.webp"},
  {name: "Father's Day", file: "father-s-day.webp"},
  {name: "Government", file: "government.webp"},
  {name: "Groundhog Day", file: "groundhog-day.webp"},
  {name: "Halloween", file: "halloween.webp"},
  {name: "Hawaiian", file: "hawaiian.webp"},
  {name: "Hipster", file: "hipster.webp"},
  {name: "Independence Day", file: "independence-day.webp"},
  {name: "International Cat Day", file: "international-cat-day.webp"},
  {name: "Labor Day", file: "labor-day.webp"},
  {name: "Lunar New Year", file: "lunar-new-year.webp"},
  {name: "MLK Day", file: "mlk-day.webp"},
  {name: "Mac Day", file: "mac-day.webp"},
  {name: "Marine", file: "marine.webp"},
  {name: "Memorial Day", file: "memorial-day.webp"},
  {name: "Mental Health Day", file: "mental-health-day.webp"},
  {name: "Mother's Day", file: "mother-s-day.webp"},
  {name: "National Cherry Day", file: "national-cherry-day.webp"},
  {name: "National Coffee Day", file: "national-coffee-day.webp"},
  {name: "National Cookie Day", file: "national-cookie-day.webp"},
  {name: "National Dessert Day", file: "national-dessert-day.webp"},
  {name: "National Dog Day", file: "national-dog-day.webp"},
  {name: "National Donut Day", file: "national-donut-day.webp"},
  {name: "National Hot Chocolate Day", file: "national-hot-chocolate-day.webp"},
  {name: "National Ice Cream Day", file: "national-ice-cream-day.webp"},
  {name: "National Pi Day", file: "national-pi-day.webp"},
  {name: "National Pickle Day", file: "national-pickle-day.webp"},
  {name: "National Pizza Day", file: "national-pizza-day.webp"},
  {name: "National Puzzle Day", file: "national-puzzle-day.webp"},
  {name: "National Relaxation Day", file: "national-relaxation-day.webp"},
  {name: "National S'mores Day", file: "national-s-mores-day.webp"},
  {name: "New Year's", file: "new-year-s.webp"},
  {name: "Oktoberfest", file: "oktoberfest.webp"},
  {name: "Paramedic", file: "paramedic.webp"},
  {name: "Pencil Checklist", file: "pencil-checklist.webp"},
  {name: "Presidents Day", file: "presidents-day.webp"},
  {name: "Pride", file: "pride.webp"},
  {name: "Programmers' Day", file: "programmers-day.webp"},
  {name: "Sailor", file: "sailor.webp"},
  {name: "Secret Service", file: "secret-service.webp"},
  {name: "Shark Week", file: "shark-week.webp"},
  {name: "Shield", file: "shield.webp"},
  {name: "Space Force", file: "space-force.webp"},
  {name: "Spring", file: "spring.webp"},
  {name: "St. Patrick's Day", file: "st-patrick-s-day.webp"},
  {name: "Star Wars Day", file: "star-wars-day.webp"},
  {name: "Steve Jobs", file: "steve-jobs.webp"},
  {name: "Summer", file: "summer.webp"},
  {name: "SysAdmin Day", file: "sysadmin-day.webp"},
  {name: "Talk Like a Pirate Day", file: "talk-like-a-pirate-day.webp"},
  {name: "Tax Day", file: "tax-day.webp"},
  {name: "Terminal Wizard", file: "terminal-wizard.webp"},
  {name: "Thanksgiving", file: "thanksgiving.webp"},
  {name: "Valentine's Day", file: "valentine-s-day.webp"},
  {name: "Veterans Day", file: "veterans-day.webp"},
  {name: "Winter", file: "winter.webp"},
  {name: "Writing", file: "writing.webp"},
];

export default LOGOS;
